platform :ios, '9.0'

target 'TeamworkSample' do
  use_frameworks!

pod 'Alamofire'
pod 'Gloss'


  target 'TeamworkSampleTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end
